---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box


suites:
- name: config
  run_list:
  - recipe[chef-client::config]
  attributes: {}
- name: service_init
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::config]
  - recipe[chef-client_test::service_init]
  - recipe[chef-client::service]
  attributes: { chef_client: { init_style: "init" } }
- name: service_runit
  run_list:
  - recipe[minitest-handler]
  - recipe[runit]
  - recipe[chef-client_test::service_runit]
  - recipe[chef-client::service]
  attributes: { chef_client: { init_style: "runit" } }
- name: cron
  run_list:
  - recipe[chef-client::cron]
  attributes: {}
- name: delete_validation
  run_list:
  - recipe[chef-client::delete_validation]
- name: cook-2092
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2092]
  - recipe[chef-client::config]
  attributes:
    chef_client:
      log_file: "client.log"
- name: cook-2169-root
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2169-root]
  - recipe[chef-client::cron]
  attributes: {}
- name: cook-2169-chef
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2169-chef]
  - recipe[chef-client::cron]
  attributes: {}
- name: cook-2086
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client_test::cook-2086]
  - recipe[chef-client::cron]
  attributes:
    chef_client:
      environment_variables: "FOO=BAR"
- name: cook-2317
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::config]
  - recipe[chef-client_test::cook-2317]
  attributes:
    ohai:
      disabled_plugins: ["passwd"]
- name: cook-1951
  run_list:
  - recipe[minitest-handler]
  - recipe[chef-client::config]
  - recipe[chef-client::service]
  - recipe[chef-client_test::cook-1951]
  attributes:
    chef_client:
      init_style: "init"
      daemon_options: ["-E cook-1951"]